services:
  snoopy:
    user: "${UID:-1000}:${GID:-1000}"
    build: 
      context: .
      dockerfile: DOCKERFILE.dev
    volumes:
      - .:/usr/src/app/
    ports:
      - "${HTTP_SERVER}:8000"
    depends_on:
      - charlie
    command: python snoopy_repo/manage.py runserver 0.0.0.0:8000
  charlie:
    image: postgres
    restart: unless-stopped
    ports: 
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - charlie-data:/var/lib/postgresql/data

volumes:
  charlie-data:
