FROM python:latest

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

RUN mkdir -p /usr/src/app/media/images
RUN chown -R 1000:1000 /usr/src/app/media

EXPOSE 8000