FROM python:latest

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

RUN whoami
RUN mkdir -p /usr/src/app/media/images
RUN chmod -R 777 /usr/src/app/media/images

RUN ls -ld /usr/src/app/media/images

EXPOSE 8000