FROM python:latest
ARG UID
ARG GID

RUN apt update && \
    apt install -y sudo && \
    addgroup --gid $GID nonroot && \
    adduser --disabled-password --gecos '' --uid $UID --gid $GID nonroot && \
    echo "nonroot ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 

USER nonroot

WORKDIR /usr/src/app
COPY --chown=nonroot:nonroot requirements.txt ./ 
RUN chmod -R 755 /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

EXPOSE 8000