name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    name: "Test docker compose on Github Pages Intance"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Docker Compose Actions
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose-actions.yml"
          up-flags: "-d --build"
          down-flags: "--volumes --remove-orphans"
          test-container: "snoopy"
          test-command: "python manage.py test ./snoopy_images"
        env: 
          HTTP_SERVER: 8000
          DB_HOST: "Charlie"
          DB_PORT: 5432
          DB_NAME: "testDb"
          DB_USER: "testuser"
          DB_PASSWORD: "test"
          ALLOWED_HOSTS: '["127.0.0.1", "localhost", "0.0.0.0"]'
          UID: 1000
          GID: 1000

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build \
          --build-arg UID=$(id -u) \
          --build-arg GID=$(id -g) \
          -t ${{ secrets.DOCKER_USERNAME }}/snoopy:latest -f DOCKERFILE .
          docker push ${{ secrets.DOCKER_USERNAME }}/snoopy:latest

        