name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    name: Test Docker Compose Dev and Prod
    runs-on: ubuntu-latest
    uses: actions/checkout@v3	

    steps:
      - name: Test Docker Compose Dev
        run: |
          docker compose -f docker-compose.dev.yml up -d
          docker compose -f docker-compose.dev.yml exec snoopy python manage.py test snoopy_images/
          docker compose -f docker-compose.dev.yml down

      - name: Test Docker Compose Prod
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml exec snoopy python manage.py test snoopy_images/
          docker compose -f docker-compose.yml down

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/snoopy:latest -f DOCKERFILE .
          docker push ${{ secrets.DOCKER_USERNAME }}/snoopy:latest
