name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Test Docker Compose Dev
      - uses: adambirds/docker-compose-action@v1.5.0
      - with:
          compose-file: "./docker-compose-dev.yml"
          up-flags: "-d --build"
          down-flags: "--volumes --remove-orphans"
          test-command: "docker-compose -f docker-compose-dev.yml exec snoopy python manage.py test ./snoopy-images"
