name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "DB_HOST=charlie" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV
          echo "DB_USER=test" >> $GITHUB_ENV
          echo "DB_PASSWORD=test" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=['127.0.0.1', 'localhost', '0.0.0.0']" >> $GITHUB_ENV
          echo "HTTP_SERVER=8000" >> $GITHUB_ENV

      - name: Set permissions for media directory
        run: |
          sudo mkdir -p ./media/images
          sudo chown -R $USER:$USER ./media

      - name: Test Docker Compose Dev
        run: |
          docker compose -f docker-compose-dev.yml up -d
          docker compose -f docker-compose-dev.yml ps
          docker compose -f docker-compose.yml exec snoopy chmod -R 777 /usr/src/app/media
          docker compose -f docker-compose-dev.yml exec snoopy python manage.py test snoopy_images/
          docker compose -f docker-compose-dev.yml down --volumes

      - name: Test Docker Compose Prod
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml ps
          docker compose -f docker-compose.yml exec snoopy python manage.py test snoopy_images/
          docker compose -f docker-compose.yml down --volumes
